version: '3.8'
services:
  my-vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    container_name: mt-vite-app-container
    stdin_open: true
    tty: true