version: '3.8'
services:
  my-vite-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    container_name: my-vite-app-dev
    stdin_open: true
    tty: true